# Generated by Django 2.2.16 on 2022-08-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220825_2222'),
        ('users', '0003_auto_20220825_0908'),
    ]

    operations = [
    ]
