# Generated by Django 2.2.16 on 2022-08-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20220826_1150'),
        ('users', '0007_auto_20220826_1311'),
    ]

    operations = [
    ]
